# Generated by Django 4.2.1 on 2023-05-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
