# Generated by Django 4.2.1 on 2023-05-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='imagem',
            field=models.ImageField(default=2, upload_to='cardapio'),
            preserve_default=False,
        ),
    ]
